language: node_js

node_js:
  - v7

sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master
    - pwa

before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'electrode-progressive-beer' ]; then cd .. && eval "mv $currentfolder electrode-progressive-beer" && cd electrode-progressive-beer; fi
  - npm install -g gulp lighthouse
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - gulp check && npm run build && npm run pwa-perf
